class FlagList {
  static List<Map<String, String>> flags = [
    {"currency": "AED", "flag": "AE"},
    {"currency": "AUD", "flag": "AU"},
    {"currency": "CAD", "flag": "CA"},
    {"currency": "CHF", "flag": "CH"},
    {"currency": "CNY", "flag": "CN"},
    {"currency": "DKK", "flag": "DK"},
    {"currency": "EGP", "flag": "EG"},
    {"currency": "EUR", "flag": "EU"},
    {"currency": "GBP", "flag": "BG"},
    {"currency": "ISK", "flag": "IS"},
    {"currency": "JPY", "flag": "JP"},
    {"currency": "KRW", "flag": "KR"},
    {"currency": "KWD", "flag": "KW"},
    {"currency": "KZT", "flag": "KZ"},
    {"currency": "LBP", "flag": "LB"},
    {"currency": "MYR", "flag": "MY"},
    {"currency": "NOK", "flag": "NO"},
    {"currency": "PLN", "flag": "PL"},
    {"currency": "RUB", "flag": "RU"},
    {"currency": "SEK", "flag": "SE"},
    {"currency": "SGD", "flag": "SG"},
    {"currency": "TRY", "flag": "TR"},
    {"currency": "UAH", "flag": "UA"},
    {"currency": "USD", "flag": "US"},
    // {"currency": "IDR", "flag": "ID"},
    // {"currency": "ILS", "flag": "IL"},
    // {"currency": "INR", "flag": "IN"},
    // {"currency": "IQD", "flag": "IQ"},
    // {"currency": "IRR", "flag": "IR"},
    // {"currency": "ISK", "flag": "IS"},
    // {"currency": "JOD", "flag": "JO"},
    // {"currency": "AUD", "flag": "AU"},
    // {"currency": "KGS", "flag": "KG"},
    // {"currency": "KHR", "flag": "KH"},
    // {"currency": "KRW", "flag": "KR"},
    // {"currency": "KWD", "flag": "KW"},
    // {"currency": "KZT", "flag": "KZ"},
    // {"currency": "LAK", "flag": "LA"},
    // {"currency": "LBP", "flag": "LB"},
    // {"currency": "LYD", "flag": "LY"},
    // {"currency": "MAD", "flag": "MA"},
    // {"currency": "MDL", "flag": "MD"},
    // {"currency": "MMK", "flag": "MM"},
    // {"currency": "MNT", "flag": "MN"},
    // {"currency": "MXN", "flag": "MX"},
    // {"currency": "MYR", "flag": "MY"},
    // {"currency": "NOK", "flag": "NO"},
    // {"currency": "NZD", "flag": "NZ"},
    // {"currency": "OMR", "flag": "OM"},
    // {"currency": "PHP", "flag": "PH"},
    // {"currency": "PKR", "flag": "PK"},
    // {"currency": "PLN", "flag": "PL"},
    // {"currency": "QAR", "flag": "QA"},
    // {"currency": "RON", "flag": "RO"},
    // {"currency": "RSD", "flag": "RS"},
    // {"currency": "AMD", "flag": "AM"},
    // {"currency": "SAR", "flag": "SA"},
    // {"currency": "SDG", "flag": "SD"},
    // {"currency": "SEK", "flag": "SE"},
    // {"currency": "SGD", "flag": "SG"},
    // {"currency": "SYP", "flag": "SY"},
    // {"currency": "THB", "flag": "TH"},
    // {"currency": "TJS", "flag": "TJ"},
    // {"currency": "TMT", "flag": "TM"},
    // {"currency": "TND", "flag": "TN"},
    // {"currency": "TRY", "flag": "TR"},
    // {"currency": "UAH", "flag": "UA"},
    // {"currency": "AED", "flag": "AE"},
    // {"currency": "UYU", "flag": "UY"},
    // {"currency": "VES", "flag": "VE"},
    // {"currency": "VND", "flag": "VN"},
    // {"currency": "XDR", "flag": "UN"},
    // {"currency": "YER", "flag": "YE"},
    // {"currency": "ZAR", "flag": "ZA"},
  ];
}
